name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出分支
        uses: actions/checkout@v4

      - name: 删除旧的 profile
        run: ls | grep -v "wiki\|cyber_chef\|osint\|profile\|blog" | xargs -i rm -rf {}

      - name: copy 新的 profile
        run: cp -r profile/* .

      - name: 更新
        run: |
          git config --local user.email "`date "+%Y%m%d%H%M%S"`+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "`date "+%Y-%m-%d_%H:%M:%S"`"
          git push origin main -f
